spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/shoecase
    username: sa
    password:
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: create
      show_sql: true
      format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always