DROP TABLE IF EXISTS `DRY`;

CREATE TABLE `DRY` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `DRY_MACHINE_STATE` VARCHAR NOT NULL,
    `DRY_MACHINE_BEHAVIOR_TIME` INT NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS `DRY_TIME`;

CREATE TABLE `DRY_TIME` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `DRY_END_TIME` TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS `LED`;

CREATE TABLE `LED` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `STATE` VARCHAR DEFAULT NULL,
    PRIMARY KEY (id)
);
